# Generated by Django 6.1.1 on 2026-09-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transport", "0001_canonical_place_identity"),
    ]

    operations = [
        migrations.AddField(
            model_name="canonicalplace",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
