# Generated by Django 6.1.1 on 2026-09-21 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transport", "0003_backfill_place_slugs"),
    ]

    operations = [
        migrations.CreateModel(
            name="GTFSFeedDataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("source_url", models.URLField(max_length=500)),
                ("archive_sha256", models.CharField(max_length=64, unique=True)),
                ("service_start_date", models.DateField(blank=True, null=True)),
                ("service_end_date", models.DateField(blank=True, null=True)),
                ("imported_at", models.DateTimeField(auto_now_add=True)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ("-imported_at",),
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("is_active",),
                        name="transport_gtfs_one_active_dataset",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="GTFSAgency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("external_id", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=300)),
                ("url", models.URLField(max_length=500)),
                ("timezone", models.CharField(max_length=100)),
                ("phone", models.CharField(blank=True, max_length=100)),
                ("language", models.CharField(blank=True, max_length=20)),
                ("fare_url", models.URLField(blank=True, max_length=500)),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agencies",
                        to="transport.gtfsfeeddataset",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GTFSRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("external_id", models.CharField(max_length=255)),
                ("short_name", models.CharField(max_length=100)),
                ("long_name", models.CharField(max_length=500)),
                ("route_type", models.IntegerField()),
                ("url", models.URLField(blank=True, max_length=500)),
                ("color", models.CharField(blank=True, max_length=20)),
                ("text_color", models.CharField(blank=True, max_length=20)),
                (
                    "agency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="routes",
                        to="transport.gtfsagency",
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routes",
                        to="transport.gtfsfeeddataset",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GTFSShapePoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("shape_external_id", models.CharField(max_length=255)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("sequence", models.PositiveIntegerField()),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shape_points",
                        to="transport.gtfsfeeddataset",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GTFSStop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("external_id", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=300)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stops",
                        to="transport.gtfsfeeddataset",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GTFSPlaceStopLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gtfs_stop_links",
                        to="transport.canonicalplace",
                    ),
                ),
                (
                    "stop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="place_links",
                        to="transport.gtfsstop",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GTFSTrip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("external_id", models.CharField(max_length=255)),
                ("service_id", models.CharField(max_length=255)),
                ("headsign", models.CharField(blank=True, max_length=500)),
                ("direction_id", models.IntegerField(blank=True, null=True)),
                ("shape_external_id", models.CharField(blank=True, max_length=255)),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trips",
                        to="transport.gtfsfeeddataset",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trips",
                        to="transport.gtfsroute",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GTFSStopTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("arrival_seconds", models.PositiveIntegerField()),
                ("departure_seconds", models.PositiveIntegerField()),
                ("sequence", models.PositiveIntegerField()),
                ("pickup_type", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("drop_off_type", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "stop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stop_times",
                        to="transport.gtfsstop",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stop_times",
                        to="transport.gtfstrip",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GTFSCalendarService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("service_id", models.CharField(max_length=255)),
                ("monday", models.BooleanField()),
                ("tuesday", models.BooleanField()),
                ("wednesday", models.BooleanField()),
                ("thursday", models.BooleanField()),
                ("friday", models.BooleanField()),
                ("saturday", models.BooleanField()),
                ("sunday", models.BooleanField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendars",
                        to="transport.gtfsfeeddataset",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("dataset", "service_id"),
                        name="transport_gtfs_calendar_dataset_service_id_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="GTFSCalendarException",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("service_id", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("exception_type", models.PositiveSmallIntegerField()),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exceptions",
                        to="transport.gtfsfeeddataset",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["dataset", "date", "service_id"],
                        name="transport_g_dataset_4d10b8_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("dataset", "service_id", "date"),
                        name="transport_gtfs_exception_dataset_service_date_unique",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="gtfsagency",
            constraint=models.UniqueConstraint(
                fields=("dataset", "external_id"),
                name="transport_gtfs_agency_dataset_external_id_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="gtfsroute",
            index=models.Index(
                fields=["dataset", "route_type"], name="transport_g_dataset_3d72b8_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="gtfsroute",
            constraint=models.UniqueConstraint(
                fields=("dataset", "external_id"),
                name="transport_gtfs_route_dataset_external_id_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="gtfsshapepoint",
            constraint=models.UniqueConstraint(
                fields=("dataset", "shape_external_id", "sequence"),
                name="transport_gtfs_shape_dataset_id_sequence_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="gtfsstop",
            constraint=models.UniqueConstraint(
                fields=("dataset", "external_id"),
                name="transport_gtfs_stop_dataset_external_id_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="gtfsplacestoplink",
            constraint=models.UniqueConstraint(
                fields=("place", "stop"), name="transport_gtfs_place_stop_link_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="gtfstrip",
            index=models.Index(
                fields=["dataset", "service_id"], name="transport_g_dataset_baab5f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="gtfstrip",
            constraint=models.UniqueConstraint(
                fields=("dataset", "external_id"),
                name="transport_gtfs_trip_dataset_external_id_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="gtfsstoptime",
            index=models.Index(
                fields=["stop", "trip", "sequence"], name="transport_g_stop_id_8732f8_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="gtfsstoptime",
            constraint=models.UniqueConstraint(
                fields=("trip", "sequence"), name="transport_gtfs_stop_time_trip_sequence_unique"
            ),
        ),
    ]
